"""Bind final scientific/document receipts without running any evaluator or renderer."""
from pathlib import Path
import hashlib,json,subprocess
P=Path(__file__).resolve().parent.parent;R=P.parents[2]
load=lambda name:json.loads((P/name).read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
src=load('document/SOURCE_VALIDATION.json');assert not src['failures']
assert src['output_sha256']['TrafficTwin_Dissertation.md']==sha(P/'TrafficTwin_Dissertation.md')
assert src['output_sha256']['TrafficTwin_Dissertation.tex']==sha(P/'TrafficTwin_Dissertation.tex')
assert load('document/RESULT_BINDINGS.json')['status']=='passed'
a=load('evidence/ANALYSIS.json');complete=load('evidence/COMPLETE.json');compact=load('evidence/CLEAN_VERIFICATION.json')
assert complete['full_attempts']==32 and complete['valid_blocks']==8 and complete['status']=='complete'
assert compact['status']=='passed'
assert a['seal_sha256']==sha(P/'confirmation/SEALED_EXECUTION.json')
files=['TrafficTwin_Dissertation.md','TrafficTwin_Dissertation.tex','CLAIM_SOURCE_MAP.md','AUTHOR_INPUTS.md','README.md','REVIEW.md','confirmation/SEALED_EXECUTION.json','evidence/ANALYSIS.json','evidence/CELL_RESULTS.json','evidence/CELL_RESULTS.csv','evidence/PAIRED_EFFECTS.csv','evidence/BLOCK_CONTROLS.json','evidence/RAW_INVENTORY.json','evidence/TIMING.json','evidence/COMPLETE.json','evidence/CLEAN_VERIFICATION.json','evidence/QUALIFICATION.json','evidence/QUALIFICATION_FOLLOWUP.json','document/SOURCE_VALIDATION.json','document/SOURCE_MAP.json','document/INTEGRATION.json','document/RESULT_BINDINGS.json']
files+=sorted(str(f.relative_to(P)) for f in (P/'assets').glob('*.svg'))
d=dict(status='completed_with_stated_boundaries',reviewed_baseline='c049f00f2247bfbd1196d5e6524de8198fdd2df7',execution_commit='c4fe33681bd11e5af429d9f2c8c7f70f2bb745f1',branch=subprocess.check_output(['git','branch','--show-current'],cwd=R,text=True).strip(),output_sha256={f:sha(P/f) for f in files},main_text_words=src['main_text_words'],section_words=src['section_words'],qualification=dict(short_attempts=8,maximum_steps=300,new_kernel_suite=False),full_study=dict(attempts=32,valid_cells=32,valid_blocks=8,failed_attempts=0,all_primary_contrasts_retained=True,analysis=a['scope']),checks=dict(source_inspection='Current sources and preserved records inspected',compact_arithmetic='Regenerated from compact evidence in a clean temporary package',raw_record_validation='All 32 new full cells and all eight four-arm block receipts; original September audits not repeated',new_full_simulations='Declared matrix only',standalone_algorithm_tests='Qualification dependency checks only; no repeat of 719-input suite',document_source_checks=src['source_checks'],separate_ai_critique='See REVIEW.md for scope, reviewed hashes, objections and response',human_author_or_supervisor_approval='Not obtained or inferred'),timing=load('evidence/TIMING.json'),compilation_performed=False,pdf_generation_performed=False,rendering_performed=False,visual_validation_performed=False,docx_work_performed=False,historical_recovery_attempted=False,push_performed=False,merge_performed=False,submission_performed=False,boundaries=['Original E0/E1/E2 raw outputs unavailable after author-reported deletion; no known backup. Historical scoring impact remains unquantified.','New finite checks verify the declared implementation; they do not physically validate it or guarantee future-stream equality.','Same morning trace and actor; eight paired blocks, approximate-normality assumption and original three-contrast family.','Raw outputs retained locally; no approved off-machine destination or transfer. Examiner access requires arrangements.','LaTeX/Markdown source checks do not establish compilation or visual correctness.','Personal contribution, independent author checking and assessment-specific AI-use decisions remain for confirmation.'])
(P/'VALIDATION.json').write_text(json.dumps(d,indent=2)+'\n')
print(json.dumps({'status':d['status'],'word_count':d['main_text_words'],'bound_files':len(files)},indent=2))
