"""Evidence-based capability manifest for the read-only TOS Data adapter."""

from traffictwin.config.capabilities import (
    CapabilityManifest,
    CapabilitySet,
    CapabilitySupport,
)


def tos_data_capability_manifest() -> CapabilityManifest:
    """Return only capabilities established by the inspected data package."""

    unknown = CapabilitySupport.UNKNOWN
    return CapabilityManifest(
        adapter="tos_data_read_only",
        supports=CapabilitySet(
            seed_import=CapabilitySupport.FALSE,
            seed_export=CapabilitySupport.FALSE,
            run_bundle_import=CapabilitySupport.FALSE,
            streaming_canonicalisation=CapabilitySupport.FALSE,
            time_windowed_metrics=CapabilitySupport.FALSE,
            latency_percentile_family=CapabilitySupport.FALSE,
            energy_metric_family=CapabilitySupport.FALSE,
            fairness_metric_family=CapabilitySupport.FALSE,
            spatial_rsu_metric_family=CapabilitySupport.FALSE,
            custom_metric_plugin_api=CapabilitySupport.FALSE,
            temporal_degradation_diagnosis=CapabilitySupport.FALSE,
            declarative_rule_authoring=CapabilitySupport.TRUE,
            fairness_disparity_diagnosis=CapabilitySupport.FALSE,
            energy_anomaly_diagnosis=CapabilitySupport.FALSE,
            nearest_flip_analysis=CapabilitySupport.FALSE,
            threshold_sensitivity_sweep=CapabilitySupport.FALSE,
            cross_rule_reasoning=CapabilitySupport.FALSE,
            paired_statistical_study=CapabilitySupport.FALSE,
            n_way_policy_ranking=CapabilitySupport.FALSE,
            equivalence_testing=CapabilitySupport.FALSE,
            regression_gate=CapabilitySupport.FALSE,
            power_analysis=CapabilitySupport.FALSE,
            difference_provenance=CapabilitySupport.FALSE,
            provenance_graph_export=CapabilitySupport.TRUE,
            provenance_completeness_score=CapabilitySupport.FALSE,
            parameter_sweep_composer=CapabilitySupport.FALSE,
            scenario_mutation_operators=CapabilitySupport.FALSE,
            measurement_noise_dropout_models=CapabilitySupport.FALSE,
            latex_research_export=CapabilitySupport.FALSE,
            analyst_annotations=CapabilitySupport.FALSE,
            structured_report_diffing=CapabilitySupport.FALSE,
            one_page_executive_summary=CapabilitySupport.FALSE,
            full_text_registry_search=CapabilitySupport.FALSE,
            registry_schema_migrations=CapabilitySupport.FALSE,
            canonical_table_caching=CapabilitySupport.FALSE,
            environment_doctor=CapabilitySupport.FALSE,
            ro_crate_archival_export=CapabilitySupport.FALSE,
            generalised_external_source_contract=CapabilitySupport.TRUE,
            direct_launch=CapabilitySupport.FALSE,
            asynchronous_launch=CapabilitySupport.FALSE,
            task_arrival_multiplier=unknown,
            workload_class_mix=unknown,
            workload_ordering=unknown,
            vehicle_count=unknown,
            vehicle_tier_mix=unknown,
            rsu_count=unknown,
            rsu_capacity=unknown,
            rsu_placement=unknown,
            rsu_failure=unknown,
            action_toggles=unknown,
            signal_timing=unknown,
            lane_closure=unknown,
        ),
    )
