"""Metric Contract Registry — metadata-only closed contracts."""

from .models import (
    REGISTRY_MAX_CONTRACTS,
    REGISTRY_SCHEMA_VERSION,
    MetricContract,
    MetricContractCompatibility,
    MetricContractCompatibilityStatus,
    MetricContractDenominator,
    MetricContractDirection,
    MetricContractFinding,
    MetricContractFindingSeverity,
    MetricContractRegistry,
    MetricContractRegistryReceipt,
    MetricContractStatus,
    MetricContractSupersession,
)
from .service import (
    build_built_in_registry,
    check_resource_strategy_compatibility,
    fingerprint_registry,
    is_built_in_metric,
    load_registry_from_dict,
    load_registry_from_file,
    load_registry_from_json,
    merge_registries,
    parse_registry_json,
    registry_to_canonical_json,
    registry_to_csv,
    registry_to_json,
    validate_registry,
)

__all__ = [
    "REGISTRY_MAX_CONTRACTS",
    "REGISTRY_SCHEMA_VERSION",
    "MetricContract",
    "MetricContractCompatibility",
    "MetricContractCompatibilityStatus",
    "MetricContractDenominator",
    "MetricContractDirection",
    "MetricContractFinding",
    "MetricContractFindingSeverity",
    "MetricContractRegistry",
    "MetricContractRegistryReceipt",
    "MetricContractStatus",
    "MetricContractSupersession",
    "build_built_in_registry",
    "check_resource_strategy_compatibility",
    "fingerprint_registry",
    "is_built_in_metric",
    "load_registry_from_dict",
    "load_registry_from_file",
    "load_registry_from_json",
    "merge_registries",
    "parse_registry_json",
    "registry_to_canonical_json",
    "registry_to_csv",
    "registry_to_json",
    "validate_registry",
]
