"""Deterministic synthetic record generation."""

from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any, TypeVar

from traffictwin.domain.enums import TaskClass
from traffictwin.domain.scenario import ScenarioSeed
from traffictwin.synthetic.config import SyntheticPolicyProfile, SyntheticScenarioConfig

ChoiceT = TypeVar("ChoiceT", str, TaskClass)


@dataclass(frozen=True)
class SyntheticRunData:
    """Generated synthetic run data ready to be written as a run bundle."""

    config: SyntheticScenarioConfig
    seed: ScenarioSeed
    rows: dict[str, list[dict[str, object | None]]]


def generate_run_data(config: SyntheticScenarioConfig) -> SyntheticRunData:
    """Generate deterministic synthetic records for one scenario config."""

    rng = random.Random(config.random_seed)  # noqa: S311 - deterministic fixture generation.
    vehicles = _vehicles(config)
    tasks = _tasks(config, vehicles, rng)
    infrastructure = _infrastructure(config, len(tasks))
    traffic = _traffic(config)
    trips = _trips(config, vehicles, rng)
    incidents = _incidents(config)
    rows: dict[str, list[dict[str, object | None]]] = {"tasks": tasks}
    if config.include_infrastructure:
        rows["infra_state"] = infrastructure
    if config.include_vehicles:
        rows["vehicle_state"] = vehicles
    if config.include_traffic:
        rows["traffic_obs"] = traffic
    if config.include_trips:
        rows["trips"] = trips
    if config.include_incidents and incidents:
        rows["incidents"] = incidents
    return SyntheticRunData(config=config, seed=_seed(config), rows=rows)


def _seed(config: SyntheticScenarioConfig) -> ScenarioSeed:
    capacity_mode = "reduced" if "reduced_rsu_capacity" in config.synthetic_faults else "standard"
    tier_mix = "weak" if config.vehicle_tier_mix.get("low", 0.0) >= 0.6 else "mixed"
    return ScenarioSeed.model_validate(
        {
            "schema_version": "1.0",
            "id": f"seed-{config.scenario_id}",
            "name": config.name,
            "description": (
                f"{config.description} Synthetic fixture generated by TrafficTwin; not real data."
            ).strip(),
            "base": config.baseline_seed_id,
            "preset_id": config.scenario_id,
            "demand": {"multiplier": max(0.1, config.congestion_multiplier)},
            "workload": {
                "birth_rate_multiplier": max(0.1, config.task_arrival_rate / 0.10),
                "class_mix": {key.value: value for key, value in config.task_class_mix.items()},
                "ordering": "mixed",
            },
            "fleet": {"count": config.vehicle_count, "tier_mix": tier_mix},
            "infrastructure": {
                "rsu_count": config.rsu_count,
                "rsu_capacity_mode": capacity_mode,
                "failed_rsus": [],
            },
            "allowed_decisions": ["local", "v2i", "v2v"],
            "policy": {"algorithm": config.policy_behavior.value, "checkpoint": None},
            "evaluation": {"random_seed": config.random_seed},
            "compare_against": config.baseline_seed_id,
            "provenance": {
                "created_by": "TrafficTwin synthetic generator",
                "source": "TrafficTwin standalone demo",
            },
        }
    )


def _vehicles(config: SyntheticScenarioConfig) -> list[dict[str, object | None]]:
    tier_sequence = _weighted_sequence(config.vehicle_tier_mix, config.vehicle_count)
    timestamps = _timestamps(config)
    rows: list[dict[str, object | None]] = []
    for index, tier in enumerate(tier_sequence, start=1):
        vehicle_id = f"veh-{index:03d}"
        base_speed = {"low": 11.0, "medium": 12.0, "high": 13.0}[tier]
        for timestamp in timestamps:
            rows.append(
                {
                    "timestamp": timestamp,
                    "vehicle_id": vehicle_id,
                    "x": round(index * 12.5 + timestamp * 0.8, 3),
                    "y": round((index % 4) * 3.5, 3),
                    "speed": round(max(1.0, base_speed / config.congestion_multiplier), 3),
                    "lane": f"lane-{(index % 3) + 1}",
                    "tier": tier,
                }
            )
    return rows


def _tasks(
    config: SyntheticScenarioConfig,
    vehicles: list[dict[str, object | None]],
    rng: random.Random,
) -> list[dict[str, object | None]]:
    unique_vehicles = _first_vehicle_rows(vehicles)
    task_count = max(1, int(round(config.duration_s * config.task_arrival_rate)))
    class_choices = _weighted_sequence(config.task_class_mix, task_count)
    rows: list[dict[str, object | None]] = []
    spacing = config.duration_s / task_count
    for index in range(task_count):
        vehicle = unique_vehicles[index % len(unique_vehicles)]
        vehicle_id = str(vehicle["vehicle_id"])
        tier = str(vehicle["tier"])
        task_class = class_choices[index]
        decision = _decision(config.policy_behavior, task_class, tier, rng)
        arrival = round(index * spacing + rng.random() * min(3.0, spacing / 2), 3)
        deadline = _deadline_ms(task_class)
        latency = _latency_ms(config, task_class, tier, decision, index, rng)
        completed = latency <= deadline * _deadline_tolerance(config, task_class, tier, decision)
        if _forced_incomplete(config, task_class, tier, decision, rng):
            completed = False
        completion_time = round(arrival + latency / 1000.0, 3) if completed else None
        rows.append(
            {
                "task_id": f"task-{config.scenario_id}-{index + 1:04d}",
                "vehicle_id": vehicle_id,
                "task_class": task_class.value,
                "arrival_time": arrival,
                "deadline_ms": deadline,
                "decision": decision,
                "completed": "true" if completed else "false",
                "completion_time": completion_time,
                "latency_ms": round(latency, 3) if completed else None,
                "target_id": _target_id(decision, index, config.rsu_count),
                "workload_cycles": _workload_cycles(task_class),
                "data_size_bytes": _data_size_bytes(task_class),
                "energy_j": round(_energy_j(task_class, decision), 3) if completed else None,
                "drop_reason": None if completed else _drop_reason(config, decision),
            }
        )
    return rows


def _infrastructure(
    config: SyntheticScenarioConfig,
    task_count: int,
) -> list[dict[str, object | None]]:
    timestamps = _timestamps(config)
    rows: list[dict[str, object | None]] = []
    for rsu_index in range(config.rsu_count):
        rsu_id = f"rsu-{rsu_index + 1}"
        for point, timestamp in enumerate(timestamps):
            utilisation = _utilisation(config, rsu_index, point, len(timestamps))
            queue = _queue_length(config, rsu_index, point, utilisation)
            arrivals = max(0, int(round(task_count / max(1, len(timestamps) * config.rsu_count))))
            rows.append(
                {
                    "timestamp": timestamp,
                    "rsu_id": rsu_id,
                    "queue_length": queue,
                    "utilisation": round(utilisation, 3),
                    "arrivals": arrivals,
                    "active_tasks": min(int(round(queue + utilisation * config.rsu_capacity)), 999),
                    "drops": max(0, int(queue - config.rsu_capacity * 0.25)),
                    "capacity": config.rsu_capacity,
                }
            )
    return rows


def _traffic(config: SyntheticScenarioConfig) -> list[dict[str, object | None]]:
    rows: list[dict[str, object | None]] = []
    for timestamp in _timestamps(config):
        pressure = config.congestion_multiplier
        speed = max(2.0, 14.0 / pressure)
        if any(
            incident.timestamp_s <= timestamp <= incident.timestamp_s + 60
            for incident in config.incident_schedule
        ):
            speed *= 0.7
        rows.append(
            {
                "timestamp": timestamp,
                "sensor_id": "sensor-corridor-a",
                "count": int(round(10 * pressure + timestamp / max(config.duration_s, 1.0) * 3)),
                "average_speed": round(speed, 3),
                "location": "synthetic-corridor-a",
            }
        )
    return rows


def _trips(
    config: SyntheticScenarioConfig,
    vehicles: list[dict[str, object | None]],
    rng: random.Random,
) -> list[dict[str, object | None]]:
    unique_vehicles = _first_vehicle_rows(vehicles)
    rows: list[dict[str, object | None]] = []
    for index in range(config.trip_count):
        departure = round(index * max(5.0, config.duration_s / max(config.trip_count, 1)), 3)
        baseline_duration = 520 + rng.randint(0, 80)
        duration = baseline_duration * config.congestion_multiplier
        if "longer_trips" in config.synthetic_faults:
            duration *= 1.25
        rows.append(
            {
                "trip_id": f"trip-{config.scenario_id}-{index + 1:03d}",
                "vehicle_id": unique_vehicles[index % len(unique_vehicles)]["vehicle_id"],
                "departure_time": departure,
                "arrival_time": round(departure + duration, 3),
                "duration": round(duration, 3),
                "route_id": "synthetic-route-a",
            }
        )
    return rows


def _incidents(config: SyntheticScenarioConfig) -> list[dict[str, object | None]]:
    return [
        {
            "incident_id": f"incident-{config.scenario_id}-{index}",
            "timestamp": incident.timestamp_s,
            "incident_type": incident.incident_type,
            "location": incident.location,
            "severity": incident.severity,
        }
        for index, incident in enumerate(config.incident_schedule, start=1)
    ]


def _timestamps(config: SyntheticScenarioConfig) -> list[float]:
    count = int(config.duration_s // config.sampling_interval_s)
    return [round(index * config.sampling_interval_s, 3) for index in range(count + 1)]


def _weighted_sequence(weights: dict[ChoiceT, float], count: int) -> list[ChoiceT]:
    ordered = sorted(weights.items(), key=lambda item: str(item[0]))
    remaining = count
    sequence: list[ChoiceT] = []
    for index, (key, share) in enumerate(ordered):
        n = remaining if index == len(ordered) - 1 else int(round(count * share))
        sequence.extend([key] * n)
        remaining -= n
    return sequence[:count]


def _first_vehicle_rows(
    vehicles: list[dict[str, object | None]],
) -> list[dict[str, object | None]]:
    seen: set[str] = set()
    rows: list[dict[str, object | None]] = []
    for row in vehicles:
        vehicle_id = str(row["vehicle_id"])
        if vehicle_id not in seen:
            seen.add(vehicle_id)
            rows.append(row)
    return rows


def _decision(
    profile: SyntheticPolicyProfile,
    task_class: TaskClass,
    tier: str,
    rng: random.Random,
) -> str:
    if profile is SyntheticPolicyProfile.ALWAYS_LOCAL:
        return "local"
    if profile is SyntheticPolicyProfile.ALWAYS_V2I:
        return "v2i"
    if profile is SyntheticPolicyProfile.RANDOM:
        return rng.choice(["local", "v2i", "v2v"])
    if profile is SyntheticPolicyProfile.LOW_OFFLOAD:
        return "local" if rng.random() < 0.92 else "v2i"
    if profile is SyntheticPolicyProfile.SELECTIVE:
        return "v2i" if task_class is TaskClass.T1 or tier == "low" else "local"
    if profile is SyntheticPolicyProfile.BALANCED:
        if task_class is TaskClass.T1:
            return "v2i" if rng.random() < 0.65 else "v2v"
        return "local" if rng.random() < 0.45 else "v2i"
    return "local"


def _deadline_ms(task_class: TaskClass) -> float:
    return {TaskClass.T1: 120.0, TaskClass.T2: 250.0, TaskClass.T3: 500.0}[task_class]


def _latency_ms(
    config: SyntheticScenarioConfig,
    task_class: TaskClass,
    tier: str,
    decision: str,
    index: int,
    rng: random.Random,
) -> float:
    class_base = {TaskClass.T1: 80.0, TaskClass.T2: 150.0, TaskClass.T3: 260.0}[task_class]
    tier_factor = {"low": 1.9, "medium": 1.25, "high": 0.9}[tier]
    jitter = rng.uniform(0.92, 1.10)
    if decision == "local":
        latency = class_base * tier_factor * jitter
    else:
        latency = (class_base * 0.82 + config.baseline_network_delay_ms) * jitter
    latency *= config.congestion_multiplier
    if "sustained_rsu_overload" in config.synthetic_faults and decision != "local":
        latency *= 1.8 + (index % 4) * 0.12
    if (
        "weak_vehicle_t1_concentration" in config.synthetic_faults
        and task_class is TaskClass.T1
        and tier == "low"
    ):
        latency *= 1.45
    return latency


def _deadline_tolerance(
    config: SyntheticScenarioConfig,
    task_class: TaskClass,
    tier: str,
    decision: str,
) -> float:
    tolerance = 1.0
    if "low_pressure" in config.synthetic_faults:
        tolerance = 2.0
    if "sustained_rsu_overload" in config.synthetic_faults and decision != "local":
        tolerance = 0.85
    if (
        "weak_vehicle_t1_concentration" in config.synthetic_faults
        and task_class is TaskClass.T1
        and tier == "low"
    ):
        tolerance = 0.9
    return tolerance


def _forced_incomplete(
    config: SyntheticScenarioConfig,
    task_class: TaskClass,
    tier: str,
    decision: str,
    rng: random.Random,
) -> bool:
    probability = 0.02 * config.congestion_multiplier
    if (
        "weak_vehicle_t1_concentration" in config.synthetic_faults
        and task_class is TaskClass.T1
        and tier == "low"
        and decision == "local"
    ):
        probability += 0.35
    if "sustained_rsu_overload" in config.synthetic_faults and decision != "local":
        probability += 0.22
    if "low_pressure" in config.synthetic_faults:
        probability = 0.01
    return rng.random() < min(probability, 0.85)


def _target_id(decision: str, index: int, rsu_count: int) -> str | None:
    if decision == "v2i":
        return f"rsu-{(index % rsu_count) + 1}"
    if decision == "v2v":
        return f"veh-{(index % 5) + 1:03d}"
    return None


def _workload_cycles(task_class: TaskClass) -> float:
    return {TaskClass.T1: 1_200_000.0, TaskClass.T2: 2_000_000.0, TaskClass.T3: 3_500_000.0}[
        task_class
    ]


def _data_size_bytes(task_class: TaskClass) -> float:
    return {TaskClass.T1: 40_000.0, TaskClass.T2: 95_000.0, TaskClass.T3: 150_000.0}[task_class]


def _energy_j(task_class: TaskClass, decision: str) -> float:
    base = {TaskClass.T1: 0.8, TaskClass.T2: 1.2, TaskClass.T3: 1.9}[task_class]
    return base if decision == "local" else base * 0.65


def _drop_reason(config: SyntheticScenarioConfig, decision: str) -> str:
    if "sustained_rsu_overload" in config.synthetic_faults and decision != "local":
        return "synthetic_rsu_queue_timeout"
    return "synthetic_deadline_miss"


def _utilisation(
    config: SyntheticScenarioConfig,
    rsu_index: int,
    point: int,
    point_count: int,
) -> float:
    base = min(
        0.82, 0.28 + config.task_arrival_rate * 1.6 + (config.congestion_multiplier - 1) * 0.12
    )
    wave = (point % 4) * 0.035
    if "spare_rsu_capacity" in config.synthetic_faults:
        base = 0.30
    if "sustained_rsu_overload" in config.synthetic_faults:
        base = (
            0.92
            if ("localised_saturation" not in config.synthetic_faults or rsu_index == 0)
            else 0.16
        )
        wave = 0.03 if point > 0 else 0.0
    if "low_pressure" in config.synthetic_faults:
        base = 0.22 + rsu_index * 0.02
        wave = 0.01
    del point_count
    return max(0.0, min(1.0, base + wave))


def _queue_length(
    config: SyntheticScenarioConfig,
    rsu_index: int,
    point: int,
    utilisation: float,
) -> int:
    if "sustained_rsu_overload" in config.synthetic_faults and (
        "localised_saturation" not in config.synthetic_faults or rsu_index == 0
    ):
        return 5 + point * 2
    if "low_pressure" in config.synthetic_faults:
        return point % 2
    return max(0, int(round(utilisation * 5 + config.congestion_multiplier - 1)))


def serialisable_rows(rows: dict[str, list[dict[str, Any]]]) -> dict[str, list[dict[str, Any]]]:
    """Return rows with deterministic key ordering for tests."""

    return {
        kind: [dict(sorted(row.items())) for row in data] for kind, data in sorted(rows.items())
    }
