"""Central metric catalogue."""

from __future__ import annotations

from traffictwin.metrics.definitions import AggregationScope, MetricDefinition, MetricDomain

METRIC_VERSION = "1.0"


def _definition(
    key: str,
    name: str,
    description: str,
    domain: MetricDomain,
    unit: str,
    scope: AggregationScope = AggregationScope.RUN,
    *,
    required_tables: list[str] | None = None,
    required_fields: dict[str, list[str]] | None = None,
    higher_is_better: bool | None = None,
    limitations: list[str] | None = None,
) -> MetricDefinition:
    return MetricDefinition(
        key=key,
        human_name=name,
        description=description,
        domain=domain,
        unit=unit,
        aggregation_scope=scope,
        required_tables=required_tables or [],
        required_fields=required_fields or {},
        implementation_version=METRIC_VERSION,
        higher_is_better=higher_is_better,
        limitations=limitations or [],
    )


METRIC_DEFINITIONS: dict[str, MetricDefinition] = {
    definition.key: definition
    for definition in [
        _definition(
            "task.generated.count",
            "Tasks generated",
            "Count of valid task records.",
            MetricDomain.TASK,
            "count",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.completed.count",
            "Tasks completed",
            "Count of valid completed task records.",
            MetricDomain.TASK,
            "count",
            required_tables=["tasks"],
            higher_is_better=True,
        ),
        _definition(
            "task.completion.rate",
            "Task completion rate",
            "Completed valid tasks divided by generated valid tasks.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=True,
        ),
        _definition(
            "task.completion.rate_by_class",
            "Completion rate by task class",
            "Completion rate grouped by task class.",
            MetricDomain.TASK,
            "ratio",
            AggregationScope.TASK_CLASS,
            required_tables=["tasks"],
            higher_is_better=True,
        ),
        _definition(
            "task.completion.rate_by_vehicle_tier",
            "Completion rate by vehicle tier",
            "Completion rate grouped by vehicle tier when vehicle evidence exists.",
            MetricDomain.TASK,
            "ratio",
            AggregationScope.VEHICLE_TIER,
            required_tables=["tasks", "vehicles"],
            higher_is_better=True,
        ),
        _definition(
            "task.deadline_miss.completed_observed_rate",
            "Completed-task deadline miss rate",
            "Deadline miss rate over completed tasks with latency and deadline values.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.incomplete.rate",
            "Incomplete task rate",
            "Incomplete valid tasks divided by generated valid tasks.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.latency.count",
            "Latency observation count",
            "Count of non-missing non-negative latency observations.",
            MetricDomain.TASK,
            "count",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.latency.mean_ms",
            "Mean latency",
            "Arithmetic mean of valid latency observations.",
            MetricDomain.TASK,
            "ms",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.latency.p50_ms",
            "P50 latency",
            "50th percentile of valid latency observations.",
            MetricDomain.TASK,
            "ms",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.latency.p95_ms",
            "P95 latency",
            "95th percentile of valid latency observations.",
            MetricDomain.TASK,
            "ms",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.decision.counts",
            "Decision counts",
            "Counts by canonical decision.",
            MetricDomain.TASK,
            "count",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.decision_share.local",
            "Local decision share",
            "Local decisions divided by recognised decisions.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.decision_share.v2i",
            "V2I decision share",
            "V2I decisions divided by recognised decisions.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.decision_share.v2v",
            "V2V decision share",
            "V2V decisions divided by recognised decisions.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.decision_share.unknown",
            "Unknown decision share",
            "Unknown decisions divided by all decisions.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.offload.rate",
            "Offload rate",
            "V2I plus V2V decisions divided by recognised decisions.",
            MetricDomain.TASK,
            "ratio",
            required_tables=["tasks"],
            higher_is_better=None,
        ),
        _definition(
            "task.drops.by_cause",
            "Drops by cause",
            "Task counts grouped by drop reason when available.",
            MetricDomain.TASK,
            "count",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "task.energy.per_completed_j",
            "Energy per completed task",
            "Mean energy per completed task when energy evidence exists.",
            MetricDomain.TASK,
            "J/task",
            required_tables=["tasks"],
            higher_is_better=False,
        ),
        _definition(
            "infra.rsu.summary",
            "Per-RSU infrastructure summary",
            "Per-RSU observations, queue, utilisation, arrivals, drops, and active-task summaries.",
            MetricDomain.INFRASTRUCTURE,
            "mixed",
            AggregationScope.RSU,
            required_tables=["infrastructure"],
            higher_is_better=None,
        ),
        _definition(
            "infra.observed_rsu.count",
            "Observed RSU count",
            "Number of RSUs observed in infrastructure records.",
            MetricDomain.INFRASTRUCTURE,
            "count",
            required_tables=["infrastructure"],
            higher_is_better=None,
        ),
        _definition(
            "infra.queue_length.mean",
            "Mean queue length",
            "Mean queue length across valid infrastructure observations.",
            MetricDomain.INFRASTRUCTURE,
            "tasks",
            required_tables=["infrastructure"],
            higher_is_better=False,
        ),
        _definition(
            "infra.queue_length.max",
            "Maximum queue length",
            "Maximum queue length across valid infrastructure observations.",
            MetricDomain.INFRASTRUCTURE,
            "tasks",
            required_tables=["infrastructure"],
            higher_is_better=False,
        ),
        _definition(
            "infra.utilisation.mean",
            "Mean utilisation",
            "Mean utilisation across valid infrastructure observations.",
            MetricDomain.INFRASTRUCTURE,
            "fraction",
            required_tables=["infrastructure"],
            higher_is_better=False,
        ),
        _definition(
            "infra.utilisation.p95",
            "P95 utilisation",
            "95th percentile utilisation across valid infrastructure observations.",
            MetricDomain.INFRASTRUCTURE,
            "fraction",
            required_tables=["infrastructure"],
            higher_is_better=False,
        ),
        _definition(
            "infra.saturation.episode_count",
            "Saturation episode count",
            "Number of per-RSU saturation episodes using configured threshold.",
            MetricDomain.INFRASTRUCTURE,
            "count",
            required_tables=["infrastructure"],
            higher_is_better=False,
        ),
        _definition(
            "infra.saturation.duration_s",
            "Saturation duration",
            "Total observed saturation duration using timestamp differences.",
            MetricDomain.INFRASTRUCTURE,
            "s",
            required_tables=["infrastructure"],
            higher_is_better=False,
            limitations=["Synthetic default threshold is not a validated research threshold."],
        ),
        _definition(
            "infra.load_balance.jain_capacity_normalised",
            "Jain capacity-normalised load balance",
            "Jain index over capacity-normalised load when capacity and load numerator exist.",
            MetricDomain.INFRASTRUCTURE,
            "index",
            required_tables=["infrastructure"],
            higher_is_better=None,
        ),
        _definition(
            "traffic.observation.count",
            "Traffic observation count",
            "Count of valid traffic observations.",
            MetricDomain.TRAFFIC,
            "count",
            required_tables=["traffic"],
            higher_is_better=None,
        ),
        _definition(
            "traffic.count.total",
            "Total traffic count",
            "Sum of available traffic count observations.",
            MetricDomain.TRAFFIC,
            "vehicles",
            required_tables=["traffic"],
            higher_is_better=None,
        ),
        _definition(
            "traffic.count.mean",
            "Mean traffic count",
            "Mean count per traffic observation.",
            MetricDomain.TRAFFIC,
            "vehicles",
            required_tables=["traffic"],
            higher_is_better=None,
        ),
        _definition(
            "traffic.speed.mean_mps",
            "Mean speed",
            "Mean traffic speed.",
            MetricDomain.TRAFFIC,
            "m/s",
            required_tables=["traffic"],
            higher_is_better=True,
        ),
        _definition(
            "traffic.speed.p50_mps",
            "P50 speed",
            "50th percentile traffic speed.",
            MetricDomain.TRAFFIC,
            "m/s",
            required_tables=["traffic"],
            higher_is_better=True,
        ),
        _definition(
            "traffic.speed.p95_mps",
            "P95 speed",
            "95th percentile traffic speed.",
            MetricDomain.TRAFFIC,
            "m/s",
            required_tables=["traffic"],
            higher_is_better=True,
        ),
        _definition(
            "traffic.speed.min_mps",
            "Minimum speed",
            "Minimum traffic speed.",
            MetricDomain.TRAFFIC,
            "m/s",
            required_tables=["traffic"],
            higher_is_better=True,
        ),
        _definition(
            "traffic.time_coverage",
            "Traffic time coverage",
            "First timestamp, last timestamp, and duration.",
            MetricDomain.TRAFFIC,
            "s",
            required_tables=["traffic"],
            higher_is_better=None,
        ),
        _definition(
            "traffic.sensor.count",
            "Traffic sensor count",
            "Number of observed sensors.",
            MetricDomain.TRAFFIC,
            "count",
            required_tables=["traffic"],
            higher_is_better=None,
        ),
        _definition(
            "trip.records.count",
            "Trip record count",
            "Total trip records.",
            MetricDomain.TRIP,
            "count",
            required_tables=["trips"],
            higher_is_better=None,
        ),
        _definition(
            "trip.completed.count",
            "Completed trip count",
            "Trip records with arrival or valid duration evidence.",
            MetricDomain.TRIP,
            "count",
            required_tables=["trips"],
            higher_is_better=True,
        ),
        _definition(
            "trip.incomplete.count",
            "Incomplete trip count",
            "Trip records without completion evidence.",
            MetricDomain.TRIP,
            "count",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "trip.completion.rate",
            "Trip completion rate",
            "Completed trips divided by total trip records.",
            MetricDomain.TRIP,
            "ratio",
            required_tables=["trips"],
            higher_is_better=True,
        ),
        _definition(
            "trip.duration.count",
            "Trip duration observation count",
            "Count of valid trip duration observations.",
            MetricDomain.TRIP,
            "count",
            required_tables=["trips"],
            higher_is_better=None,
        ),
        _definition(
            "trip.duration.mean_s",
            "Mean trip duration",
            "Mean valid trip duration.",
            MetricDomain.TRIP,
            "s",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "trip.duration.p50_s",
            "P50 trip duration",
            "50th percentile trip duration.",
            MetricDomain.TRIP,
            "s",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "trip.duration.p95_s",
            "P95 trip duration",
            "95th percentile trip duration.",
            MetricDomain.TRIP,
            "s",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "trip.duration.min_s",
            "Minimum trip duration",
            "Minimum valid trip duration.",
            MetricDomain.TRIP,
            "s",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "trip.duration.max_s",
            "Maximum trip duration",
            "Maximum valid trip duration.",
            MetricDomain.TRIP,
            "s",
            required_tables=["trips"],
            higher_is_better=False,
        ),
        _definition(
            "comparison.absolute_delta",
            "Absolute delta",
            "Variation metric value minus baseline metric value.",
            MetricDomain.COMPARISON,
            "metric_unit",
            AggregationScope.SEED_PAIR,
            higher_is_better=None,
        ),
        _definition(
            "comparison.relative_delta",
            "Relative delta",
            "Absolute delta divided by the absolute baseline value, "
            "with explicit zero-baseline handling.",
            MetricDomain.COMPARISON,
            "ratio",
            AggregationScope.SEED_PAIR,
            higher_is_better=None,
        ),
        _definition(
            "comparison.seed_aligned_difference",
            "Seed-aligned difference",
            "Difference for runs aligned by experiment and random seed where required.",
            MetricDomain.COMPARISON,
            "metric_unit",
            AggregationScope.SEED_PAIR,
            higher_is_better=None,
        ),
    ]
}


def metric_catalogue() -> dict[str, MetricDefinition]:
    """Return the central metric catalogue ordered by key."""

    return {key: METRIC_DEFINITIONS[key] for key in sorted(METRIC_DEFINITIONS)}


def get_metric_definition(key: str) -> MetricDefinition:
    """Return a metric definition by key."""

    return METRIC_DEFINITIONS[key]
